schema:
  - src/services/ds/graphql/schema.graphql
documents:
  - './**/*.tsx'
  - './**/*.ts'
generates:
  src/generated/:
    preset: client
    plugins: [ ]
    presetConfig:
      fragmentMasking: false
